dojo.declare("classes.managers.NummonStatsManager",com.nuclearunicorn.core.TabManager,{game:null,lang:"en",i18ng:null,i18nData:{en:{catnip:"Catnip / Sec",getCatnipInWarmSpring:"During Warm Spring",getCatnipColdWinter:"During Cold Winter",science:"Science",getCelestialPerDay:"Chance of Celestial Events",getCelestialAutoSuccess:"Celestial Event Auto Success Rate",getMaxComped:"Maximum Helpful Compediums",getBlueprintCraft:"Blueprints Per Craft",titanium:"Titanium",getTitPerZebraTrade:"Titanium Per Zebra Trade",
getZebraTradesLeftToMaxTit:"Trades Left to Cap Titanium",getZebraTradesToMaxTit:"Max Zebra Trades to Cap Titanium",pollution:"\u6c61\u67d3",getPollutionTick:"pollution per second",getCoMax:"Max of CO2",unicorns:"Unicorns",getBestUniBuilding:"Best Unicorn Building",getBestAliBuilding:"Best Alicorn Building Per Ivory Cost",getNecrocornsPerSecond:"Necrocorns Per Second",getNecrocornTime:"Time Until Next Necrocorn",getLeviChance:"Chance per year of Leviathans",religion:"Religion",getReligionProductionBonusCap:"Solar Revolution Limit",
getlowestRatio:"\u4e0b\u4e00\u6b21\u5143\u8d85\u8d8a\u7b49\u7ea7\u51cf\u5c11\u7684\u987f\u609f",getNextTranscendTierProgress:"Progress to Next Transcendence Tier",getRecNextTranscendTierProgress:"Rec.Progress to Next Transcendence Tier",paragon:"Paragon Bonus",getParagonProductionBonus:"Production Bonus",getParagonStorageBonus:"Storage Bonus(include horizon)",time:"Time",getTCPerSacrifice:"Time Crystals per Sacrifice",getRelicPerTCRefine:"Relics Per Time Crystal Refine",resourceRetrieval:"\u8d44\u6e90\u56de\u590d",
getTradeTC:"\u6bcf\u8df3\u4e00\u5e74\u7684\u65f6\u95f4\u6c34\u6676\u8d38\u6613\u6536\u5165",getResourceRetrievalTCBackYears:"\u4e0b\u7ea7\u8d44\u6e90\u56de\u590d\u4e8f\u635f\u81f3\u76c8\u5229\u7684\u65f6\u95f4",others:"Others",getBestMagnetoBuilding:"Best Magneto/Steamwork Building",getUraniumForThoriumReactors:"Uranium/Sec for Thorium Reactors",getDarkFutureYears:"Years until Dark Future",getBestRelicBuilding:"Best improve Relic Building",getAIlv15Time:"Time until AI level 15",getFutureSeason:"Seasons until next TemporalParadox",
getadjustDay:"Time until 1100 Crypto Price","best.none":"No Building",infinity:"Infinity",sec:"/sec",done:"Done"},zh:{catnip:"\u732b\u8584\u8377 / \u79d2",getCatnipInWarmSpring:"\u6696\u6625",getCatnipColdWinter:"\u5bd2\u51ac",science:"\u79d1\u5b66",getCelestialPerDay:"\u5929\u6587\u4e8b\u4ef6\u6bcf\u5929\u51fa\u73b0\u7684\u51e0\u7387",getCelestialAutoSuccess:"\u5929\u6587\u4e8b\u4ef6\u81ea\u52a8\u89c2\u6d4b\u7684\u51e0\u7387",getMaxComped:"\u589e\u52a0\u79d1\u5b66\u5e93\u5b58\u7684\u6982\u8981\u6570\u91cf\u4e0a\u9650",
getBlueprintCraft:"\u6bcf\u6b21\u5de5\u827a\u5236\u4f5c\u7684\u84dd\u56fe",titanium:"\u949b",getTitPerZebraTrade:"\u6bcf\u6b21\u548c\u6591\u9a6c\u8d38\u6613\u83b7\u5f97\u7684\u949b",getZebraTradesLeftToMaxTit:"\u949b\u6ee1\u4ed3\u8fd8\u9700\u8981\u4e0e\u6591\u9a6c\u8d38\u6613(\u6b21)",getZebraTradesToMaxTit:"\u949b\u4ece\u96f6\u81f3\u6ee1\u4ed3\u603b\u5171\u8981\u4e0e\u6591\u9a6c\u8d38\u6613(\u6b21)",pollution:"\u6c61\u67d3",getPollutionTick:"\u4e8c\u6c27\u5316\u78b3\u6392\u653e\u91cf",getCoMax:"\u4e8c\u6c27\u5316\u78b3\u6700\u5927\u503c",
unicorns:"\u72ec\u89d2\u517d\u5b97\u6559",getBestUniBuilding:"\u6700\u4f73\u72ec\u89d2\u517d\u5efa\u7b51",getBestAliBuilding:"\u8c61\u7259\u6027\u4ef7\u6bd4\u6700\u9ad8\u5929\u89d2\u517d\u5efa\u7b51",getNecrocornsPerSecond:"\u6bcf\u79d2\u83b7\u5f97\u7684\u6b7b\u7075\u517d",getNecrocornTime:"\u8ddd\u79bb\u4e0b\u4e00\u4e2a\u6b7b\u7075\u517d\u7684\u65f6\u95f4",getLeviChance:"\u5229\u7ef4\u5766\u6bcf\u5e74\u5230\u6765\u964d\u4e34\u7684\u51e0\u7387",religion:"\u592a\u9633\u6559\u56e2",getReligionProductionBonusCap:"\u592a\u9633\u9769\u547d\u6781\u9650\u52a0\u6210",
getNextTranscendTierProgress:"\u5f53\u524d\u987f\u609f\u503c",getAdore:"\u8d5e\u7f8e\u7fa4\u661f\u540e\u7684\u987f\u609f\u503c",getAdoreSloar:"\u8d5e\u7f8e\u7fa4\u661f\u518d\u8d5e\u7f8e\u592a\u9633\u7684\u592a\u9633\u9769\u547d\u52a0\u6210",Transcend:"\u6b21\u5143\u8d85\u8d8a",getlowestRatio:"\u8fdb\u884c\u6b21\u5143\u8d85\u8d8a\u7684\u987f\u609f\u51cf\u5c11\u503c",getRecNextTranscendTierProgress:"\u63a8\u8350\u6b21\u5143\u8d85\u8d8a\u7684\u5f53\u524d\u987f\u609f\u503c",getBoolean:"\u8d5e\u7f8e\u7fa4\u661f\u524d(\u662f/\u5426)\u6b21\u5143\u8d85\u8d8a",
paragon:"\u9886\u5bfc\u529b\u52a0\u6210",getParagonProductionBonus:"\u751f\u4ea7\u52a0\u6210",getParagonStorageBonus:"\u5e93\u5b58\u52a0\u6210(\u542b\u9ed1\u6d1e)",getEffectLeader:"\u9886\u8896\u7279\u8d28\u6548\u679c",time:"\u65f6\u95f4",getTCPerSacrifice:"\u6bcf\u6b21\u5929\u89d2\u517d\u732e\u796d\u7684\u65f6\u95f4\u6c34\u6676\u503c",getRelicPerTCRefine:"\u6bcf\u6b21\u65f6\u95f4\u6c34\u6676\u7cbe\u70bc\u7684\u9057\u7269\u503c",resourceRetrieval:"\u8d44\u6e90\u56de\u590d",getTradeTC:"\u5f53\u524d\u5468\u671f\u70e7\u6c34\u6676\u7684\u6c34\u6676\u8d38\u6613\u6536\u5165",
getTradeTCAvg:"\u5e73\u5747\u5468\u671f\u70e7\u6c34\u6676\u7684\u6c34\u6676\u5e73\u5747\u6536\u5165",getResourceRetrievalTCBackYears:"\u5347\u7ea7\u540e\u70e7\u6c34\u6676\u4f7f\u6c34\u6676\u56de\u672c\u7684\u9884\u8ba1\u65f6\u95f4",others:"\u5176\u4ed6",getBestMagnetoBuilding:"\u6700\u4f73\u78c1\u7535\u673a/\u84b8\u6c7d\u5de5\u574a",getUraniumForThoriumReactors:"\u6bcf\u79d2\u948d\u53cd\u5e94\u5806\u7b49\u6548\u603b\u8017\u94c0",getDarkFutureYears:"\u8ddd\u79bb\u9ed1\u6697\u672a\u6765\u7684\u60e9\u7f5a(\u5e74)",
getBestRelicBuilding:"\u83b7\u53d6\u6700\u4f73\u9057\u7269\u5efa\u7b51",getBestUnobtainiumBuilding:"\u96be\u5f97\u7d20\u6700\u4f73\u592a\u7a7a\u5efa\u7b51",getAIlv15Time:"\u5929\u7f51\u89c9\u9192\u5012\u8ba1\u65f6(\u73b0\u5b9e)",getFutureSeason:"\u8ddd\u79bb\u4e0b\u6b21\u65f6\u95f4\u6096\u8bba(\u5b63\u8282)",getadjustDay:"\u9ed1\u5e01\u6700\u9ad8\u4ef7\u683c\u671f\u671b\u5012\u8ba1\u65f6(\u73b0\u5b9e)","best.none":"\u65e0",infinity:"\u221e",sec:"/\u79d2",done:"\u5df2\u5b8c\u6210"}},i18n:function(a,
b){if("$"==a[0])return this.i18ng(a.slice(1));var c=this.i18nData[this.lang][a];if(!c){c=this.i18nData.en[a];if(!c)return console.error('key "'+a+'" not found'),"$"+a;console.error('key "'+a+'" not found in '+this.lang)}if(b)for(a=0;a<b.length;a++)c=c.replace("{"+a+"}",b[a]);return c},roundThisNumber:function(a){a=Math.floor(1E3*a+.5);return a/1E3},getButton:function(a,b){for(var c in this.game.tabs[a].children)if(this.game.tabs[a].children[c].opts.building==b)return parseInt(c)},getButtonPrice:function(a,
b,c,d){b=this.game[a].meta[b];for(let g=0;g<b.meta.length;g++)if(b.meta[g].name==c){var e=b.meta[g];break}for(c=0;c<e.prices.length;c++)if(e.prices[c].name==d){var f=e.prices[c].val;break}d=e.priceRatio;"bld"==a&&(d+=game.getEffect("priceRatio"));return f*Math.pow(d,e.on)},makeNiceString:function(a,b=3){if("number"==typeof a&&Infinity!=a)for(a=a.toFixed(b),a=a.toString(),a.substr(a.indexOf("."))=="."+Array(b+1).join("0")&&(a=a.substr(0,a.indexOf("."))),b=-1!=a.indexOf(".")?a.indexOf(".")-3:a.length-
3;0<b;b-=3)a=a.substr(0,b)+","+a.substr(b);else a=a.toString();return a},getPotentialCatnip:function(a){a*=this.game.getEffect("catnipPerTickBase");var b=this.game.village.getResProduction().catnip?this.game.village.getResProduction().catnip*(1+this.game.getEffect("catnipJobRatio")):0;a=(a+b)*(1+this.game.getEffect("catnipRatio"));b=this.game.challenges.isActive("winterIsComing")?0:this.game.prestige.getParagonProductionRatio();a=a*(1+b)*(1+this.game.religion.getSolarRevolutionRatio()*(1+this.game.bld.pollutionEffects.solarRevolutionPollution));
a*=1+this.game.getEffect("blsProductionBonus")*this.game.resPool.get("sorrow").value;a=this.game.calendar.cycleEffectsFestival({catnip:a}).catnip;a*=1+this.game.bld.pollutionEffects.catnipPollutionRatio;b=this.game.village.getResConsumption().catnip;b*=1+this.game.getEffect("catnipDemandRatio");if(0<this.game.village.sim.kittens.length&&1<this.game.village.happiness){var c=Math.max(this.game.village.happiness*(1+this.game.getEffect("hapinnessConsumptionRatio"))-1,0);b=this.game.challenges.isActive("anarchy")?
b*(1+c*(1+this.game.getEffect("catnipDemandWorkerRatioGlobal"))):b*(1+c*(1+this.game.getEffect("catnipDemandWorkerRatioGlobal"))*(1-this.game.village.getFreeKittens()/this.game.village.sim.kittens.length))}a+=b;a+=this.game.getResourcePerTickConvertion("catnip");a*=1+this.game.timeAccelerationRatio();return a*=this.game.ticksPerSecond},getCatnipColdWinter:function(){var a=this.game.calendar.seasons,b;for(b in a)if("winter"==a[b].name){var c=a[b].modifiers.catnip;break}c=(c-.15)*(1+this.game.getLimitedDR(this.game.getEffect("coldHarshness"),
1));game.science.getPolicy("communism").researched&&(c=0);return this.getPotentialCatnip(c)},getCatnipInWarmSpring:function(){var a=this.game.calendar.seasons,b;for(b in a)if("spring"==a[b].name){var c=a[b].modifiers.catnip;break}c=(c+.15)*(1+this.game.getLimitedDR(this.game.getEffect("springCatnipRatio"),2));return this.getPotentialCatnip(c)},getCelestialPerDay:function(){var a=1;this.game.prestige.getPerk("chronomancy").researched&&(a*=1.1);a*=1+.25*this.game.getEffect("timeRatio");var b=25+1E4*
this.game.getEffect("starEventChance");b*=.01*a;this.game.prestige.getPerk("astromancy").researched&&(b*=2);return game.getDisplayValueExt(b)+"%"},getCelestialAutoSuccess:function(){var a=100*this.game.getEffect("starAutoSuccessChance");this.game.prestige.getPerk("astromancy").researched&&(a*=2);game.ironWill&&(a=Math.max(26,a));a=Math.round(a);if(100<a||this.game.workshop.get("seti").researched)a=100;return a+"%"},getMaxComped:function(){var a=this.game.bld.getEffect("scienceMax"),b=this.game.bld.getEffect("scienceMaxCompendia"),
c=this.game.ironWill?10:1,d=this.game.religion.getTU("blackLibrary");this.game.prestige.getPerk("codexLeviathanianus").researched&&(d=.05*(1+d.val*(d.effects.compendiaTTBoostRatio+this.game.getEffect("blackLibraryBonus"))),c*=1+d*this.game.religion.transcendenceTier);return(a*c+b)/10},getBlueprintCraft:function(){var a=this.game.getResCraftRatio("blueprint"),b=game.getCraftRatio()!=a,c=game.science.get("physics").researched;return b||c?1+a:this.i18n("best.none")},getTitPerZebraTrade:function(){var a=
this.game.resPool.get("ship").value,b=.015*this.game.getEffect("zebraRelationModifier");return(1.5+.03*a)*(1+b)},getZebraTradesToMaxTit:function(){var a=this.getTitPerZebraTrade(),b=this.game.resPool.get("titanium").maxValue;return Math.ceil(b/a)},getZebraTradesLeftToMaxTit:function(){var a=this.getTitPerZebraTrade(),b=this.game.resPool.get("titanium").maxValue;b-=this.game.resPool.get("titanium").value;b=Math.ceil(b/a);0>b&&(b=0);return b},getPollutionTick:function(){if(!this.game.science.get("ecology").researched)return this.i18n("best.none");
var a=this.game.opts.forceHighPrecision?3:2,b=this.game.bld.cathPollutionPerTick*this.game.getTicksPerSecondUI();if(0==this.game.bld.cathPollution||!b)return 0;b*=1E-5;if(1>=Math.abs(b)){b=b.toPrecision(a);var c=b.toString();c.match("e-")&&(b=c.split("e-"),b=Number(c).toFixed(Number(b[1])+a-1))}else b=b.toFixed(a);a="+ ";0>=b&&(a="");return a+b+"/"+$I("unit.sec")},getCoMax:function(){if(!this.game.science.get("ecology").researched)return this.i18n("best.none");var a=100*this.game.bld.getUndissipatedPollutionPerTick();
a=Math.max(a,0);this.game.challenges.isActive("postApocalypse")&&a&&(a="\u221e");return a},getBestUniBuilding:function(a){if("undefined"===typeof this.getButton(0,"unicornPasture"))return this.i18n("best.none");a="unicornTomb ivoryTower ivoryCitadel skyPalace unicornUtopia sunspire".split(" ");var b=this.game.getEffect("unicornsPerTickBase")*this.game.getTicksPerSecondUI(),c=this.game.getEffect("unicornsGlobalRatio")+1,d=this.game.getEffect("unicornsRatioReligion")+1,e=this.game.prestige.getParagonProductionRatio()+
1,f=this.game.religion.getSolarRevolutionRatio()+1,g=1;void 0!=this.game.calendar.cycles[this.game.calendar.cycle].festivalEffects.unicorns&&this.game.prestige.getPerk("numeromancy").researched&&this.game.calendar.festivalDays&&(g=this.game.calendar.cycles[this.game.calendar.cycle].festivalEffects.unicorns);var w=Math.max(this.game.bld.getBuildingExt("ziggurat").meta.on,1),x=b*c*(this.game.getEffect("unicornsRatioReligion")+1)*e*f*g,r=500*(1+.1*this.game.getEffect("unicornsRatioReligion")),t=1;this.game.prestige.getPerk("unicornmancy").researched&&
(t*=1.1);r*=this.game.getEffect("riftChance")*t/2E4;var p=Infinity,m="",h=this.game.bld.getBuildingExt("unicornPasture").meta.effects.unicornsPerTickBase*this.game.getTicksPerSecondUI();h=h*c*(this.game.getEffect("unicornsRatioReligion")+1)*e*f*g;h=this.getButtonPrice("bld",0,"unicornPasture","unicorns")/h;h<p&&(p=h,m="$buildings.unicornPasture.label");for(var v in this.game.tabs[5].zgUpgradeButtons)if(h=this.game.tabs[5].zgUpgradeButtons[v],-1!=a.indexOf(h.id)&&h.model.visible){var l=this.game.religion.getZU(h.id),
u=0;u+=[5,25,50,500,5E3,25E3][v]*Math.pow(1.15,this.game.religion.getZU(h.id).on)*2500/w;var q=game.getEffect("unicornsRatioReligion")+1,k=this.game.getEffect("riftChance"),n;for(n in l.effects)"unicornsRatioReligion"==n&&(q+=l.effects[n]),"riftChance"==n&&(k+=l.effects[n]);l=k*t/2E4*500*(.1*(q-1)+1);l-=r;k=b*c*q*e*f*g;k-=x;k+=l;k=u/k;if(k<p)if(0<l||q>d&&0<u)p=k,m=h.id;else return game.religionTab.render()}"$buildings.unicornPasture.label"!=m&&(m="$religion.zu."+m+".label");return this.i18n(m)},getBestAliBuilding:function(){var a=
["best.none","$religion.zu.skyPalace.label","$religion.zu.unicornUtopia.label","$religion.zu.sunspire.label"];if(!this.game.religion.getZU("skyPalace").unlocked)return this.i18n(a[0]);var b=125*1.15**this.game.religion.getZU("skyPalace").val,c=1E3*1.15**this.game.religion.getZU("unicornUtopia").val,d=750*1.15**this.game.religion.getZU("sunspire").val;b=[b,c,d];return this.i18n(a[b.indexOf(Math.min(...b))+1])},getNecrocornsPerSecond:function(){var a=this.game.resPool.get("alicorn").value,b=1+Math.sqrt(this.game.resPool.get("sorrow").value*
this.game.getEffect("blsCorruptionRatio")),c=1;0<this.game.resPool.get("necrocorn").value&&(c=.25*(1+this.game.getEffect("corruptionBoostRatio")));c*=this.game.getEffect("corruptionRatio")*b;0>=a&&(c=0);c*=this.game.getTicksPerSecondUI();c=1*c.toPrecision(this.game.opts.forceHighPrecision?3:2);return Infinity==c?this.i18n("infinity"):c+this.i18n("sec")},getNecrocornTime:function(){var a=this.game.resPool.get("alicorn").value,b=this.game.religion.corruption,c=1+Math.sqrt(this.game.resPool.get("sorrow").value*
this.game.getEffect("blsCorruptionRatio")),d=1;0<this.game.resPool.get("necrocorn").value&&(d=.25*(1+this.game.getEffect("corruptionBoostRatio")));d*=this.game.getEffect("corruptionRatio")*c;0>=a&&(d=b=0);return 0==d?this.i18n("infinity"):this.game.toDisplaySeconds((1-b)/(d*this.game.getTicksPerSecondUI()))},getLeviChance:function(){var a=this.game.religion.getZU("blackPyramid").getEffectiveValue(this.game),b=this.game.religion.getZU("marker").val;a=3.5*a*(1+.1*b);return 100<a?100:1*this.game.getDisplayValueExt(a)+
"%"},getReligionProductionBonusCap:function(){var a=100*(10+this.game.getEffect("solarRevolutionLimit")+(this.game.challenges.getChallenge("atheism").researched?this.game.religion.transcendenceTier:0))*(1+this.game.getLimitedDR(this.game.getEffect("faithSolarRevolutionBoost"),4));a=this.game.getDisplayValueExt(a);return a+"%"},getAdore:function(){if(!game.religion.meta[1].meta[8].on)return this.i18n("best.none");var a=(this.game.religion.getRU("transcendence").on?this.game.religion.transcendenceTier:
0)+1;return this.game.religion.faithRatio+1E-6*this.game.religion.faith*a*a*1.01},getAdoreSloar:function(){if(!game.religion.getRU("solarRevolution").on||!game.religion.meta[1].meta[8].on)return this.i18n("best.none");var a=(this.game.religion.getRU("transcendence").on?this.game.religion.transcendenceTier:0)+1;a=.01+this.game.resPool.resources[14].value*(1+.1*game.getUnlimitedDR(this.game.religion.faithRatio+1E-6*this.game.religion.faith*a*a*1.01,.1));a=this.game.getUnlimitedDR(a,1E3)/100;a=this.game.getLimitedDR(a,
10+this.game.getEffect("solarRevolutionLimit")+(this.game.challenges.getChallenge("atheism").researched?this.game.religion.transcendenceTier:0))*(1+this.game.getLimitedDR(this.game.getEffect("faithSolarRevolutionBoost"),4))*100;return this.game.getDisplayValueExt(a)+"%"},getlowestRatio:function(){var a=this.game.religion.transcendenceTier+1;return this.game.religion._getTranscendTotalPrice(a)-game.religion._getTranscendTotalPrice(a-1)},getRecNextTranscendTierProgress:function(){if(355<=this.game.religion.transcendenceTier)return"\u221e";
var a=this.game.religion.transcendenceTier+1,b=this.game.religion._getTranscendTotalPrice(a)-game.religion._getTranscendTotalPrice(a-1),c=this.game.religion.getTU("blackObelisk").val;a=(5*a*c+1E3)/(5*this.game.religion.transcendenceTier*c+1E3)*Math.pow((a+1)/a,2);a=b-.0125+.0125*Math.pow((Math.sqrt((80*a*b+361*a-361+80*b)/(a-1))-19*a)/(a+1),2);return 2.02*game.religion.faith*this.game.religion.transcendenceTier+3.03*game.religion.faith>=1E6*b&&this.game.religion.faithRatio>b?b:Math.max(a,b)},getNextTranscendTierProgress:function(){return 355<=
this.game.religion.transcendenceTier?"\u221e":this.game.religion.faithRatio},getBoolean:function(){if(!game.religion.getRU("transcendence").on||354<=this.game.religion.transcendenceTier)return this.i18n("best.none");var a=this.game.religion.transcendenceTier+1,b=this.game.religion._getTranscendTotalPrice(a)-game.religion._getTranscendTotalPrice(a-1);var c=this.game.religion.faithRatio<this.getRecNextTranscendTierProgress()?"\u5426":"\u662f";2.02*this.game.religion.faith*(a-1)+3.03*this.game.religion.faith>=
1E6*b&&this.game.religion.faithRatio>b?c="\u662f":1E5>this.game.religion.faith&&(c="\u5426\uff08\u8654\u8bda\u592a\u5c11\uff09");return c},getParagonProductionBonus:function(){var a=100*this.game.prestige.getParagonProductionRatio();a=Math.round(1E3*a)/1E3;return a+"%"},getParagonStorageBonus:function(){var a=1+this.game.prestige.getParagonStorageRatio(),b=1+this.game.getEffect("globalResourceRatio");a=this.game.getDisplayValueExt(100*a*b-100);return a+"%"},getEffectLeader:function(){if(!game.village.leader)return this.i18n("best.none");
let a=[{name:"faith",val:100},{name:"science",val:100}],b=this.game.village.getEffectLeader(this.game.village.leader.trait.name,a);return 100!=a[0].val?"\u00d7 "+game.getDisplayValueExt(a[0].val)+"%":100!=a[1].val?"* "+game.getDisplayValueExt(a[1].val)+"%":game.getDisplayValueExt(100*b)+"%"},getTCPerSacrifice:function(){return 1+this.game.getEffect("tcRefineRatio")},getRelicPerTCRefine:function(){return 1+this.game.getEffect("relicRefineRatio")*this.game.religion.getZU("blackPyramid").getEffectiveValue(this.game)},
getTradeTC:function(){var a=1+this.game.diplomacy.getTradeRatio()+this.game.diplomacy.calculateTradeBonusFromPolicies("leviathans",this.game)+this.game.challenges.getChallenge("pacifism").getTradeBonusEffect(this.game),b=this.game.calendar;b=b.ticksPerDay*b.daysPerSeason*b.seasonsPerYear;var c=this.game.diplomacy.get("leviathans"),d=1+.02*c.energy;for(f of c.sells)if("timeCrystal"==f.name){var e=f.value*f.chance/c.buys[0].val;break}a*=e*this.game.getResourcePerTick("unobtainium")*d;var f=this.game.getEffect("shatterTCGain")*
(1+this.game.getEffect("rrRatio"));return a*b*f},getTradeTCAvg:function(){var a=this.game.calendar.cycleEffectsFestival({unobtainium:1}).unobtainium,b=this.game.calendar.cycleEffectsBasics({unobtainiumPerTickSpace:1},"moonOutpost").unobtainiumPerTickSpace;a=(56.5+12*this.game.getEffect("festivalRatio"))/50*this.getTradeTC()/a/b;b=this.game.getEffect("shatterTCGain")*(1+this.game.getEffect("rrRatio"));var c=this.game.getEffect("alicornChance"),d=.04*(1+this.game.getEffect("tcRefineRatio"));c*=1+this.game.getLimitedDR(game.getEffect("alicornPerTickRatio"),
1.2);c=.2*Math.min(c,1)*(1+this.game.timeAccelerationRatio());var e=this.game.getResourcePerTick("alicorn")*d;return a+(4E3*e*b+c*d)},getResourceRetrievalTCBackYears:function(){var a=1+this.game.getLimitedDR(this.game.getEffect("shatterCostReduction"),1),b=this.game.calendar.cycleEffectsFestival({unobtainium:1}).unobtainium,c=this.game.calendar.cycleEffectsBasics({unobtainiumPerTickSpace:1},"moonOutpost").unobtainiumPerTickSpace;b=this.getTradeTC()/c/b;c=this.game.challenges.getChallenge("1000Years").researched?
5:10;a=b-100/(100+c)*a;b*=(56.5+12*game.getEffect("festivalRatio"))/50;c=this.getButtonPrice("time",0,"ressourceRetrieval","timeCrystal");var d=this.game.time.getCFU("ressourceRetrieval").val;if(this.game.time.getCFU("ressourceRetrieval").unlocked){if(100==d)return this.i18n("best.none");if(0>=a)return"\u70e7\u6c34\u6676\u6536\u5165\u672a\u5927\u4e8e\u71c3\u70e7\u6c34\u6676\u652f\u51fa";a=Math.ceil(c*d/b);b=game.time.getCFU("blastFurnace").on;return this.game.toDisplaySeconds(50*a/b)}return this.i18n("$time.cfu.ressourceRetrieval.label")},
getUraniumForThoriumReactors:function(){if(!game.workshop.get("thoriumReactors").researched)return this.i18n("best.none");var a=-.001*(1-game.getEffect("uraniumRatio"))*this.game.bld.getBuildingExt("reactor").meta.on,b=250*game.getEffect("reactorThoriumPerTick")*this.game.bld.getBuildingExt("reactor").meta.on;b/=1+this.game.getResCraftRatio("thorium");b=(b+a)*this.game.getTicksPerSecondUI();return game.getDisplayValueExt(b)+this.i18n("sec")},getBestRelicBuilding:function(){if(!this.game.religion.getZU("blackPyramid").val)return this.i18n("$religion.zu.blackPyramid.label");
if(!this.game.religion.getTU("blackNexus").on)return this.i18n("$religion.tu.blackNexus.label");var a=Math.floor(Math.log((15+this.game.religion.getZU("blackPyramid").getEffectiveValue(this.game))/5)/Math.log(1.15))+1;var b=0,c=Math.ceil(this.getButtonPrice("religion",0,"blackPyramid","sorrow"))-this.game.resPool.get("sorrow").maxValue,d=this.getButtonPrice("religion",2,"blackNexus","relic"),e=this.getButtonPrice("religion",2,"blackCore","relic");e*=(Math.pow(1.15,c)-1)/.15;var f=.001*a/d,g=.001*
this.game.religion.getTU("blackNexus").val/e;if(0<c&&f>=g){for(;f>=g&&d<Number.MAX_VALUE/1.15;)d*=1.15,f=.001*a/d,g+=.001/e,b++;a=this.i18n("$religion.tu.blackNexus.label")+" +"+b+"\u4e2a"}else a=this.i18n("$religion.tu.blackCore.label")+" +"+c+"\u4e2a",1>c&&(a=this.i18n("$religion.zu.blackPyramid.label"));return a},getBestUnobtainiumBuilding:function(){if(!game.science.get("nanotechnology").researched)return this.i18n("best.none");var a=this.getButtonPrice("space",1,"spaceElevator","unobtainium"),
b=this.getButtonPrice("space",4,"orbitalArray","eludium");game.space.getBuilding("spaceElevator");game.space.getBuilding("orbitalArray");var c=1+this.game.getEffect("spaceRatio"),d=(.01+c)*b*1E3,e=(.02+c)*a*(1+this.game.getCraftRatio("chemist"));if(d>=e){if(a>game.resPool.resources[9].maxValue)return this.i18n("best.none");for(var f=1;d>=e&&a<Number.MAX_VALUE/1.15;)a*=1.15,c+=.01,e=(.02+c)*a*(1+this.game.getCraftRatio("chemist")),d=(.01+c)*b*1E3,f++;return $I("space.planet.cath.spaceElevator.label")+
" +"+f+"\u4e2a"}return $I("space.planet.piscine.orbitalArray.label")},getDarkFutureYears:function(){var a=this.game.calendar.darkFutureYears(!0);return 0>a?this.game.getDisplayValueExt(-a):this.i18n("done")},getAIlv15Time:function(){if(this.game.science.getPolicy("transkittenism").researched)return this.i18n("best.none");var a=Math.exp(14.5),b=this.game.resPool.get("gflops").value,c=this.game.getEffect("gflopsPerTickBase")-this.game.getEffect("gflopsConsumption");return 15<=this.game.bld.get("aiCore").effects.aiLevel?
this.i18n("done"):0<c?this.game.toDisplaySeconds((a-b)/(c*this.game.getTicksPerSecondUI())):this.i18n("infinity")},getFutureSeason:function(){var a=this.game.calendar.futureSeasonTemporalParadox;return 0==this.game.bld.get("chronosphere").on?this.i18n("best.none"):-1==a?1:a+1},getadjustDay:function(){if(this.game.science.get("antimatter").researched&&(this.game.science.get("blackchain").researched||0<this.game.resPool.get("blackcoin").value)){var a=Math.floor(Math.log(1100/game.calendar.cryptoPrice)/
Math.log(1.0000012495));return 2<a?this.game.toDisplaySeconds(2*a):this.i18n("best.none")}return this.i18n("best.none")},stats:{catnip:[{name:"getCatnipInWarmSpring",val:0},{name:"getCatnipColdWinter",title:"\u5927\u4e8e 0 \u624d\u4e0d\u4f1a\u997f\u6b7b\u55b5\u55b5\u5462",val:0}],science:[{name:"getCelestialPerDay",val:0},{name:"getCelestialAutoSuccess",val:0},{name:"getMaxComped",val:0},{name:"getBlueprintCraft",val:0}],titanium:[{name:"getTitPerZebraTrade",val:0},{name:"getZebraTradesLeftToMaxTit",
val:0}],pollution:[{name:"getPollutionTick",val:0},{name:"getCoMax",val:0}],unicorns:[{name:"getBestUniBuilding",val:0},{name:"getNecrocornsPerSecond",val:0},{name:"getLeviChance",val:0}],religion:[{name:"getReligionProductionBonusCap",val:0},{name:"getNextTranscendTierProgress",val:0},{name:"getAdore",val:0},{name:"getAdoreSloar",title:"\u4f9b\u73c2\u5b66\u5bb6\u8d5e\u7f8e\u7fa4\u661f\u89e6\u53d1\u6761\u4ef6\u53c2\u8003",val:0}],Transcend:[{name:"getlowestRatio",val:0},{name:"getRecNextTranscendTierProgress",
title:"\u6709\u8fd9\u4e48\u591a\u987f\u609f\u518d\u6b21\u5143\u8d85\u8d8a\u662f\u6700\u6548\u7387\u7684\u55b5~",val:0},{name:"getBoolean",val:0}],paragon:[{name:"getParagonProductionBonus",val:0},{name:"getParagonStorageBonus",val:0},{name:"getEffectLeader",val:0}],time:[{name:"getTCPerSacrifice",val:0},{name:"getRelicPerTCRefine",val:0}],resourceRetrieval:[{name:"getTradeTC",val:0},{name:"getTradeTCAvg",val:0},{name:"getResourceRetrievalTCBackYears",title:"\u8d44\u6e90\u56de\u590d\u7684\u56de\u672c\u65f6\u95f4\uff0c\u4ec5\u4f9b\u53c2\u8003",
val:0}],others:[{name:"getUraniumForThoriumReactors",val:0},{name:"getDarkFutureYears",val:0},{name:"getBestRelicBuilding",val:0},{name:"getBestUnobtainiumBuilding",val:0},{name:"getAIlv15Time",title:"\u5c0f\u5fc3\u673a\u5668\u4eba",val:0},{name:"getFutureSeason",title:"\u975e\u914b\u7a0b\u5ea6",val:0},{name:"getadjustDay",val:0}]},statDefinitions:[{name:"catnip"},{name:"science"},{name:"titanium"},{name:"pollution"},{name:"unicorns"},{name:"religion"},{name:"Transcend"},{name:"paragon"},{name:"time"},
{name:"resourceRetrieval"},{name:"others"}],statGroups:null,constructor:function(a,b,c){this.game=a;this.i18ng=b;this.statGroups=[];var d=this;this.lang=c&&this.i18nData[c]?c:"en";this.statDefinitions.forEach(function(g){d.statGroups.push({group:d.stats[g.name],title:d.i18n(g.name)})});for(var e in this.statGroups)for(var f in this.statGroups[e].group)this.statGroups[e].group[f].calculate=this[this.statGroups[e].group[f].name]},getStat:function(a){return this[a]()},save:function(a){},load:function(a){},
resetState:function(){}});
dojo.declare("classes.tab.NummonTab",com.nuclearunicorn.game.ui.tab,{container:null,constructor:function(a){},render:function(a){this.container=a;game.religionTab.render();this.update()},update:function(){dojo.empty(this.container);for(var a in this.game.nummon.statGroups){var b=this.game.nummon.statGroups[a];dojo.create("h1",{innerHTML:b.title},this.container);b=b.group;var c=dojo.create("table",{class:"statTable"},this.container),d;for(d in b){var e=b[d],f=e.val;Infinity==f&&(f="Infinity");e.val=
this.game.nummon[e.name]();var g=dojo.create("tr",null,c);dojo.create("td",{innerHTML:this.game.nummon.i18n(e.name),title:e.title?e.title:""},g);dojo.create("td",{innerHTML:"number"==typeof f?this.game.getDisplayValueExt(f):f},g)}}}});
NummonInit=function(){var a=$I,b=localStorage["com.nuclearunicorn.kittengame.language"],c=[{id:"nummon",class:"NummonStatsManager"}],d;for(d in c){var e=c[d];void 0==gamePage[e.id]?(gamePage[e.id]=new window.classes.managers[e.class](gamePage,a,b),gamePage.managers.push(gamePage[e.id])):gamePage[e.id]=new window.classes.managers[e.class](gamePage,a,b)}gamePage.nummonTab=new classes.tab.NummonTab({name:"Nummon",id:"Nummon"},gamePage);gamePage.nummonTab.visible=!0;a=!1;for(d in gamePage.tabs)"Nummon"==
gamePage.tabs[d].tabId&&(gamePage.tabs[d]=gamePage.nummonTab,a=!0);a||gamePage.addTab(gamePage.nummonTab);"zh"==localStorage["com.nuclearunicorn.kittengame.language"]&&(gamePage.nummonTab.tabName="\u6982\u89c8");gamePage.render(!0);gamePage.getTab=function(f){switch(f){case "science":return this.libraryTab;case "village":return this.villageTab;case "workshop":return this.workshopTab;case "space":return this.spaceTab;case "stats":return this.statsTab;case "nummon":return this.nummonTab;case "time":return this.timeTab;
case "challenges":return this.challengesTab}}};NummonTryInit=function(){"undefined"===typeof gamePage?setTimeout(function(){NummonTryInit()},2E3):NummonInit()};
box=function(){if(0==this.game.resPool.get("elderBox").value&&0==this.gamePage.resPool.get("wrappingPaper").value){let a=(new Date).getTime(),b=(new Date(2022,0,26)).getTime(),c=(new Date(2022,1,7)).getTime();a>=b&&a<c&&$.ajax({cache:!1,type:"GET",dataType:"JSON",crossDomain:!0,url:"https://worldtimeapi.org/api/ip/"}).done(function(d){d&&(d=d.day_of_year,26<=d&&38>=d&&(game.resPool.get("elderBox").value++,game.msg("\u65b0\u5e74\u5feb\u4e50\uff0cCheney\u9001\u4e86\u4f60\u4e00\u4efd\u793c\u7269\u76d2",
"important"),game.karmaKittens||(game.karmaKittens+=5,game.msg("\u65b0\u5e74\u5feb\u4e50\uff0cCheney\u9001\u4e86\u4f60\u4e00\u4efd\u4e1a","important"))))})}};var haveMsg;
spring=function(){var a=(new Date(2022,1,1)).getTime(),b=(new Date).getTime();if(-6E5<a+6E5-b)var c=setInterval(function(){var d=(new Date).getTime();d=(new Date(2022,1,1)).getTime()-d;0<d?(new Date).getTime():-6E5<d&&0>=d&&!haveMsg&&(game.msg("Cheney\u795d\u4f60\u65b0\u5e74\u5feb\u4e50","important"),haveMsg=!0,clearInterval(c))},1E3)};
dailySign=function(){var a=localStorage.sign||0,b=(new Date).getFullYear().toString();b=Math.ceil((new Date-new Date(b))/864E5);b>a&&38>=b&&38>=a&&$.ajax({cache:!1,type:"GET",dataType:"JSON",crossDomain:!0,url:"https://worldtimeapi.org/api/ip/"}).done(function(c){if(c){var d=Math.floor(3*Math.random());if(0===d){var e=game.resPool.get("ship").value;if(!e)return;do d++;while(Math.floor(2*Math.random()));e=Math.max(.01*game.resPool.get("ship").value,1);game.resPool.addResEvent("ship",d);game.msg("\u9664\u65e7\u8fce\u65b0\uff0cCheney\u9001\u4e0a"+
game.getDisplayValueExt(d*e)+" \u4e2a\u8d38\u6613\u8239","important")}else if(1===d){e=game.resPool.get("starchart").value;if(!e)return;do d++;while(Math.floor(2*Math.random()));e=Math.max(.01*game.resPool.get("starchart").value,1);game.resPool.addResEvent("starchart",d);game.msg("\u9664\u65e7\u8fce\u65b0\uff0cCheney\u9001\u4e0a"+game.getDisplayValueExt(d*e)+" \u661f\u56fe","important")}else if(2===d){e=game.resPool.get("unobtainium").value;if(!e)return;do d++;while(Math.floor(2*Math.random()));e=
Math.max(game.resPool.get("unobtainium").perTickCached,1);game.resPool.addResEvent("unobtainium",d*e);game.msg("\u9664\u65e7\u8fce\u65b0\uff0cCheney\u9001\u4e0a"+game.getDisplayValueExt(d*e)+" \u96be\u5f97\u7d20","important")}localStorage.sign=c.day_of_year}})};NummonTryInit();
